# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  # 静态资源配置
  web:
    resources:
      add-mappings: false
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
      location: ./tmp
  # 邮件服务配置
  mail:
    host: smtp.qq.com
    username: 3646959247@qq.com
    password: ehflgnpiuxkhdacb
    port: 587
    properties:
      from: 3646959247@qq.com
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: false
            protocols: TLSv1.2
          connectiontimeout: 5000
          timeout: 5000
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
    timeout: 5000ms
    connect-timeout: 5000

# 文件上传路径配置
file:
  upload-dir: ./uploads
  avatar-base-url: /uploads/avatars/

# 调试配置
debug: true

# 日志级别配置
logging:
  level:
    com.xiaoRed: debug